# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: UNCALCULABLE LIFE
subtitle:
description:
author: lambda.catノ
language: zh-tw
timezone:

# Profile picture
avatar: /images/avatar.jpg
favicon: /images/favicon.ico

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://nobodyzxc.github.io
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

social:
    Blogger: https://incalpcs.blogspot.com || google
    YouTube: https://www.youtube.com/channel/UCPgvp2rLwglsLVCrqVlQXuA || youtube
    Instagram: https://www.instagram.com/nobodyzxc.tw/ || instagram
    GitHub: https://github.com/nobodyzxc || github

#links_title: GameLinks
#links:
#    2048: /2048
#    tank: /3dtank
#    打磚塊: /BreakoutClone


# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render: [mycode/** , 3dtank/**, BreakoutClone/**]

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
#RSS订阅
plugin:
- hexo-generator-feed
#Feed Atom
feed:
type: atom
path: atom.xml
limit: 20
## Themes: https://hexo.io/themes/
theme: next

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo : git@github.com:nobodyzxc/nobodyzxc.github.io.git
  branch: master 
# message board by Disqus
disqus_shortname: https-nobodyzxc-github-io

# --------------------------------------------------------------
# background settings
# --------------------------------------------------------------
# add canvas-nest effect
# see detail from https://github.com/hustcc/canvas-nest.js
canvas_nest: true
